import esbuild from "esbuild";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the source code repository of this plugin.
*/
`;

const prod = (process.argv[2] === "production");

const builtins = [
  "path", "fs", "util", "stream", "buffer", "crypto",
  "events", "os", "child_process", "http", "https",
  "url", "net", "tls", "zlib", "assert", "dns",
  "querystring", "readline", "vm"
];

const config = {
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    ...builtins
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  minify: prod,
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
};

async function run() {
  const context = await esbuild.context(config);
  if (prod) {
    await context.rebuild();
    console.log("Build complete.");
    process.exit(0);
  } else {
    await context.watch();
    console.log("Watching for changes...");
  }
}

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
