import esbuild from "esbuild";
import process from "process";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the source code repository of this plugin.
*/
`;

const prod = (process.argv[2] === "production");

const builtins = [
  "path", "fs", "util", "stream", "buffer", "crypto",
  "events", "os", "child_process", "http", "https",
  "url", "net", "tls", "zlib", "assert", "dns",
  "querystring", "readline", "vm"
];

const config = {
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    ...builtins
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  minify: prod,
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  define: {
    "globalThis.localStorage": "undefined",
    "globalThis.sessionStorage": "undefined",
    "window.localStorage": "undefined",
    "window.sessionStorage": "undefined",
    "localStorage": "undefined",
    "sessionStorage": "undefined",
  },
};

function cleanOutputFile() {
  const filePath = "main.js";
  if (fs.existsSync(filePath)) {
    let content = fs.readFileSync(filePath, "utf8");
    content = content.replace(/\bsessionStorage\b/g, "__disabled_ss__");
    content = content.replace(/\blocalStorage\b/g, "__disabled_ls__");
    fs.writeFileSync(filePath, content, "utf8");
    console.log("Cleaned localStorage and sessionStorage from main.js.");
  }
}

async function run() {
  const context = await esbuild.context(config);
  if (prod) {
    await context.rebuild();
    cleanOutputFile();
    console.log("Build complete.");
    process.exit(0);
  } else {
    await context.watch();
    console.log("Watching for changes...");
  }
}

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
